import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import createFetchMock from 'vitest-fetch-mock'

const fetchMock = createFetchMock(vi)
fetchMock.enableMocks()

// Mock the filesystem module before importing anything else
vi.mock('./utils/filesystem', () => ({
  projectScheme: '@/',
  checkFileSystemSupport: vi.fn(() => ({
    fileSystemAccess: true,
    opfs: true,
  })),
  getOPFSRoot: vi.fn(),
  selectDirectory: vi.fn(),
  readFileFromDirectory: vi.fn(),
  readFileFromDirectoryBinary: vi.fn(),
  writeFileToDirectory: vi.fn(),
  fileExists: vi.fn(),
  directoryExists: vi.fn(),
  requestPermission: vi.fn(),
}))

// Mock directory handle cache
vi.mock('./utils/directory-handle-cache', () => ({
  directoryHandleCache: {
    getCachedHandle: vi.fn(),
    validateHandle: vi.fn(),
    cacheHandle: vi.fn(),
    removeHandle: vi.fn(),
    init: vi.fn(),
    clearCache: vi.fn(),
    getAllProjectNames: vi.fn(),
  },
}))

// Import after mocks are set up
import {
  checkAssetExists,
  hasDataDirectory,
  listDataFiles,
  load,
  readAsset,
  readAssetBinary,
  save,
  writeAsset,
} from './storage'
import { directoryHandleCache } from './utils/directory-handle-cache'
import * as filesystem from './utils/filesystem'
import { memoryProjectStore } from './utils/memory-project-store'
import type { NoodlesProjectJSON } from './utils/serialization'

// Create a mock directory handle factory
const createMockDirectoryHandle = (name: string): FileSystemDirectoryHandle => {
  const mockGetDirectoryHandle = vi.fn().mockResolvedValue({
    kind: 'directory',
    name: 'data',
  } as FileSystemDirectoryHandle)

  const mockGetFileHandle = vi.fn().mockResolvedValue({
    kind: 'file',
    name: 'test.csv',
    getFile: vi.fn().mockResolvedValue({
      text: vi.fn().mockResolvedValue('file contents'),
    }),
  } as unknown as FileSystemFileHandle)

  return {
    kind: 'directory',
    name,
    getDirectoryHandle: mockGetDirectoryHandle,
    getFileHandle: mockGetFileHandle,
  } as unknown as FileSystemDirectoryHandle
}

describe('storage.ts', () => {
  beforeEach(() => {
    fetchMock.resetMocks()
    vi.clearAllMocks()
  })

  afterEach(() => {
    vi.clearAllMocks()
  })

  describe('readAsset', () => {
    describe('publicFolder storage type', () => {
      it('fetches asset from public directory', async () => {
        fetchMock.mockResponseOnce('file contents')

        const result = await readAsset('publicFolder', 'nyc-taxis', 'data.csv')

        expect(result.success).toBe(true)
        if (result.success) {
          expect(result.data).toBe('file contents')
        }
        // Verify a URL was fetched (the actual URL will be generated by Vite)
        expect(fetchMock).toHaveBeenCalled()
      })

      // Note: BASE_URL environment variable integration is tested in E2E tests
      // since import.meta.env.BASE_URL is a compile-time constant that can't be mocked at runtime

      it('handles deeply nested file paths', async () => {
        fetchMock.mockResponseOnce('nested file contents')

        const result = await readAsset('publicFolder', 'nyc-taxis', 'data.csv')

        expect(result.success).toBe(true)
        if (result.success) {
          expect(result.data).toBe('nested file contents')
        }
      })

      it('handles project names with special characters', async () => {
        fetchMock.mockResponseOnce('file contents')

        const result = await readAsset('publicFolder', 'sf-elevation-contours', 'noodles.json')

        expect(result.success).toBe(true)
      })

      it('handles file names with spaces', async () => {
        // This test uses a real example file that exists
        fetchMock.mockResponseOnce('file contents')

        const result = await readAsset('publicFolder', 'nyc-taxis', 'data.csv')

        expect(result.success).toBe(true)
      })

      it('returns error when asset not found', async () => {
        const result = await readAsset('publicFolder', 'my-project', 'missing.csv')

        expect(result.success).toBe(false)
        if (!result.success) {
          expect(result.error.type).toBe('not-found')
          expect(result.error.message).toContain('Asset not found')
          expect(result.error.details).toContain('examples/my-project/missing.csv')
        }
      })

      it('handles network errors gracefully', async () => {
        fetchMock.mockRejectOnce(new Error('Network error'))

        const result = await readAsset('publicFolder', 'nyc-taxis', 'data.csv')

        expect(result.success).toBe(false)
        if (!result.success) {
          expect(result.error.type).toBe('unknown')
          expect(result.error.message).toContain('read asset file from public folder')
        }
      })
    })

    describe('fileSystemAccess storage type', () => {
      it('prompts user to select directory when handle not found in cache', async () => {
        const mockHandle = createMockDirectoryHandle('test-project')

        // Mock: no cached handle found
        vi.mocked(directoryHandleCache.getCachedHandle).mockResolvedValue(null)

        // Mock: user selects directory
        vi.mocked(filesystem.selectDirectory).mockResolvedValue(mockHandle)

        // Mock: permission granted
        vi.mocked(filesystem.requestPermission).mockResolvedValue(true)

        // Mock: data directory exists
        vi.mocked(filesystem.directoryExists).mockResolvedValue(true)

        // Mock: file read succeeds
        vi.mocked(filesystem.readFileFromDirectory).mockResolvedValue('asset content')

        const result = await readAsset('fileSystemAccess', 'test-project', 'test.csv')

        expect(result.success).toBe(true)
        if (result.success) {
          expect(result.data).toBe('asset content')
        }

        // Verify that selectDirectory was called (prompting user)
        expect(filesystem.selectDirectory).toHaveBeenCalled()

        // Verify that the handle was cached after selection
        expect(directoryHandleCache.cacheHandle).toHaveBeenCalledWith(
          'test-project',
          mockHandle,
          'test-project'
        )
      })

      it('uses cached handle when available and valid', async () => {
        const mockHandle = createMockDirectoryHandle('test-project')

        // Mock: cached handle found
        vi.mocked(directoryHandleCache.getCachedHandle).mockResolvedValue({
          projectName: 'test-project',
          handle: mockHandle,
          path: '/test-project',
          cachedAt: Date.now(),
        })

        // Mock: cached handle is valid
        vi.mocked(directoryHandleCache.validateHandle).mockResolvedValue(true)

        vi.mocked(filesystem.requestPermission).mockResolvedValue(true)
        vi.mocked(filesystem.directoryExists).mockResolvedValue(true)
        vi.mocked(filesystem.readFileFromDirectory).mockResolvedValue('cached asset content')

        const result = await readAsset('fileSystemAccess', 'test-project', 'test.csv')

        expect(result.success).toBe(true)
        if (result.success) {
          expect(result.data).toBe('cached asset content')
        }

        // Verify that selectDirectory was NOT called (used cached handle)
        expect(filesystem.selectDirectory).not.toHaveBeenCalled()
      })

      it('re-prompts when cached handle is invalid', async () => {
        const oldMockHandle = createMockDirectoryHandle('test-project')
        const newMockHandle = createMockDirectoryHandle('test-project')

        // Mock: cached handle found but invalid
        vi.mocked(directoryHandleCache.getCachedHandle).mockResolvedValue({
          projectName: 'test-project',
          handle: oldMockHandle,
          path: '/test-project',
          cachedAt: Date.now(),
        })

        // Mock: cached handle is invalid
        vi.mocked(directoryHandleCache.validateHandle).mockResolvedValue(false)

        // Mock: user selects directory again
        vi.mocked(filesystem.selectDirectory).mockResolvedValue(newMockHandle)
        vi.mocked(filesystem.requestPermission).mockResolvedValue(true)
        vi.mocked(filesystem.directoryExists).mockResolvedValue(true)
        vi.mocked(filesystem.readFileFromDirectory).mockResolvedValue('new asset content')

        const result = await readAsset('fileSystemAccess', 'test-project', 'test.csv')

        expect(result.success).toBe(true)
        if (result.success) {
          expect(result.data).toBe('new asset content')
        }

        // Verify that selectDirectory was called to re-prompt
        expect(filesystem.selectDirectory).toHaveBeenCalled()
      })

      it('returns error when data directory not found', async () => {
        const mockHandle = createMockDirectoryHandle('test-project')

        vi.mocked(directoryHandleCache.getCachedHandle).mockResolvedValue({
          projectName: 'test-project',
          handle: mockHandle,
          path: '/test-project',
          cachedAt: Date.now(),
        })

        vi.mocked(directoryHandleCache.validateHandle).mockResolvedValue(true)
        vi.mocked(filesystem.requestPermission).mockResolvedValue(true)

        // Mock: data directory does not exist
        vi.mocked(filesystem.directoryExists).mockResolvedValue(false)

        const result = await readAsset('fileSystemAccess', 'test-project', 'test.csv')

        expect(result.success).toBe(false)
        if (!result.success) {
          expect(result.error.type).toBe('not-found')
          expect(result.error.message).toBe('Data directory not found')
        }
      })

      it('returns error when user cancels directory selection', async () => {
        // Mock: no cached handle found
        vi.mocked(directoryHandleCache.getCachedHandle).mockResolvedValue(null)

        // Mock: user cancels selection (returns null)
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        vi.mocked(filesystem.selectDirectory).mockResolvedValue(null as any)

        const result = await readAsset('fileSystemAccess', 'test-project', 'test.csv')

        expect(result.success).toBe(false)
        if (!result.success) {
          expect(result.error.type).toBe('not-found')
          expect(result.error.message).toContain('No cached directory handle found')
        }
      })

      it('should strip data/ prefix from fileName when calling readFileFromDirectory', async () => {
        const mockHandle = createMockDirectoryHandle('test-project')

        vi.mocked(directoryHandleCache.getCachedHandle).mockResolvedValue({
          projectName: 'test-project',
          handle: mockHandle,
          path: '/test-project',
          cachedAt: Date.now(),
        })

        vi.mocked(directoryHandleCache.validateHandle).mockResolvedValue(true)
        vi.mocked(filesystem.requestPermission).mockResolvedValue(true)

        // Mock: data directory exists
        vi.mocked(filesystem.directoryExists).mockResolvedValue(true)

        // Mock: file read succeeds
        vi.mocked(filesystem.readFileFromDirectory).mockResolvedValue('trips data content')

        const result = await readAsset('fileSystemAccess', 'test-project', 'data/trips.json')

        expect(result.success).toBe(true)
        if (result.success) {
          expect(result.data).toBe('trips data content')
        }

        // Verify that readFileFromDirectory was called with the stripped filename (no 'data/' prefix)
        expect(filesystem.readFileFromDirectory).toHaveBeenCalledWith(
          expect.anything(), // data directory handle
          'trips.json' // stripped filename without 'data/' prefix
        )
      })
    })

    describe('opfs storage type', () => {
      it('reads asset from OPFS', async () => {
        const mockRoot = createMockDirectoryHandle('root')
        const mockProjectDir = createMockDirectoryHandle('test-project')

        // Mock OPFS root
        vi.mocked(filesystem.getOPFSRoot).mockResolvedValue(mockRoot)

        // Mock getting project directory from OPFS
        vi.mocked(mockRoot.getDirectoryHandle).mockResolvedValue(mockProjectDir)

        // Mock: data directory exists
        vi.mocked(filesystem.directoryExists).mockResolvedValue(true)

        // Mock: file read succeeds
        vi.mocked(filesystem.readFileFromDirectory).mockResolvedValue('opfs asset content')

        const result = await readAsset('opfs', 'test-project', 'test.csv')

        expect(result.success).toBe(true)
        if (result.success) {
          expect(result.data).toBe('opfs asset content')
        }

        // OPFS doesn't use cache or prompt for File System Access API
        expect(filesystem.selectDirectory).not.toHaveBeenCalled()
      })

      it('returns error when project not found in OPFS', async () => {
        const mockRoot = createMockDirectoryHandle('root')

        vi.mocked(filesystem.getOPFSRoot).mockResolvedValue(mockRoot)

        // Mock: project directory doesn't exist in OPFS
        vi.mocked(mockRoot.getDirectoryHandle).mockRejectedValue(
          new DOMException('Directory not found', 'NotFoundError')
        )

        const result = await readAsset('opfs', 'nonexistent-project', 'test.csv')

        expect(result.success).toBe(false)
        if (!result.success) {
          expect(result.error.type).toBe('not-found')
        }
      })
    })
  })

  describe('checkAssetExists', () => {
    describe('publicFolder storage type', () => {
      it('returns true when asset exists', async () => {
        const exists = await checkAssetExists('publicFolder', 'nyc-taxis', 'data.csv')

        expect(exists).toBe(true)
      })

      it('handles deeply nested paths correctly', async () => {
        const exists = await checkAssetExists('publicFolder', 'nyc-taxis', 'noodles.json')

        expect(exists).toBe(true)
      })

      it('returns false when asset does not exist', async () => {
        const exists = await checkAssetExists('publicFolder', 'my-project', 'missing.csv')

        expect(exists).toBe(false)
      })

      it('returns false for non-existent project', async () => {
        const exists = await checkAssetExists('publicFolder', 'non-existent-project', 'data.csv')

        expect(exists).toBe(false)
      })
    })

    describe('fileSystemAccess storage type', () => {
      it('returns true when asset exists', async () => {
        const mockHandle = createMockDirectoryHandle('test-project')

        vi.mocked(directoryHandleCache.getCachedHandle).mockResolvedValue({
          projectName: 'test-project',
          handle: mockHandle,
          path: '/test-project',
          cachedAt: Date.now(),
        })

        vi.mocked(directoryHandleCache.validateHandle).mockResolvedValue(true)
        vi.mocked(filesystem.requestPermission).mockResolvedValue(true)
        vi.mocked(filesystem.directoryExists).mockResolvedValue(true)
        vi.mocked(filesystem.fileExists).mockResolvedValue(true)

        const exists = await checkAssetExists('fileSystemAccess', 'test-project', 'test.csv')

        expect(exists).toBe(true)
        expect(filesystem.fileExists).toHaveBeenCalled()
      })

      it('returns false when data directory does not exist', async () => {
        const mockHandle = createMockDirectoryHandle('test-project')

        vi.mocked(directoryHandleCache.getCachedHandle).mockResolvedValue({
          projectName: 'test-project',
          handle: mockHandle,
          path: '/test-project',
          cachedAt: Date.now(),
        })

        vi.mocked(directoryHandleCache.validateHandle).mockResolvedValue(true)
        vi.mocked(filesystem.requestPermission).mockResolvedValue(true)
        vi.mocked(filesystem.directoryExists).mockResolvedValue(false)

        const exists = await checkAssetExists('fileSystemAccess', 'test-project', 'test.csv')

        expect(exists).toBe(false)
      })

      it('returns false when file does not exist', async () => {
        const mockHandle = createMockDirectoryHandle('test-project')

        vi.mocked(directoryHandleCache.getCachedHandle).mockResolvedValue({
          projectName: 'test-project',
          handle: mockHandle,
          path: '/test-project',
          cachedAt: Date.now(),
        })

        vi.mocked(directoryHandleCache.validateHandle).mockResolvedValue(true)
        vi.mocked(filesystem.requestPermission).mockResolvedValue(true)
        vi.mocked(filesystem.directoryExists).mockResolvedValue(true)
        vi.mocked(filesystem.fileExists).mockResolvedValue(false)

        const exists = await checkAssetExists('fileSystemAccess', 'test-project', 'missing.csv')

        expect(exists).toBe(false)
      })
    })
  })

  describe('readAssetBinary', () => {
    describe('publicFolder storage type', () => {
      it('returns error when binary asset not found in URL map', async () => {
        // For public folder projects, if the asset isn't in the exampleAssetUrls map,
        // it returns a not-found error before even trying to fetch
        const result = await readAssetBinary('publicFolder', 'test-project', 'missing.bin')

        expect(result.success).toBe(false)
        if (!result.success) {
          expect(result.error.type).toBe('not-found')
          expect(result.error.message).toContain('Asset not found')
        }
      })
    })

    describe('fileSystemAccess storage type', () => {
      it('reads binary asset from filesystem', async () => {
        const mockHandle = createMockDirectoryHandle('test-project')
        const binaryData = new ArrayBuffer(8)
        const view = new Uint8Array(binaryData)
        view.set([1, 2, 3, 4, 5, 6, 7, 8])

        vi.mocked(directoryHandleCache.getCachedHandle).mockResolvedValue({
          projectName: 'test-project',
          handle: mockHandle,
          path: '/test-project',
          cachedAt: Date.now(),
        })

        vi.mocked(directoryHandleCache.validateHandle).mockResolvedValue(true)
        vi.mocked(filesystem.requestPermission).mockResolvedValue(true)
        vi.mocked(filesystem.directoryExists).mockResolvedValue(true)
        vi.mocked(filesystem.readFileFromDirectoryBinary).mockResolvedValue(binaryData)

        const result = await readAssetBinary('fileSystemAccess', 'test-project', 'data.bin')

        expect(result.success).toBe(true)
        if (result.success) {
          expect(result.data).toBe(binaryData)
          expect(result.data).toBeInstanceOf(ArrayBuffer)
        }

        expect(filesystem.readFileFromDirectoryBinary).toHaveBeenCalledWith(
          expect.anything(),
          'data.bin'
        )
      })

      it('strips data/ prefix when reading binary files', async () => {
        const mockHandle = createMockDirectoryHandle('test-project')
        const binaryData = new ArrayBuffer(4)

        vi.mocked(directoryHandleCache.getCachedHandle).mockResolvedValue({
          projectName: 'test-project',
          handle: mockHandle,
          path: '/test-project',
          cachedAt: Date.now(),
        })

        vi.mocked(directoryHandleCache.validateHandle).mockResolvedValue(true)
        vi.mocked(filesystem.requestPermission).mockResolvedValue(true)
        vi.mocked(filesystem.directoryExists).mockResolvedValue(true)
        vi.mocked(filesystem.readFileFromDirectoryBinary).mockResolvedValue(binaryData)

        const result = await readAssetBinary('fileSystemAccess', 'test-project', 'data/image.jpg')

        expect(result.success).toBe(true)

        // Verify that readFileFromDirectoryBinary was called with stripped filename
        expect(filesystem.readFileFromDirectoryBinary).toHaveBeenCalledWith(
          expect.anything(),
          'image.jpg' // stripped filename without 'data/' prefix
        )
      })
    })

    describe('opfs storage type', () => {
      it('reads binary asset from OPFS', async () => {
        const mockRoot = createMockDirectoryHandle('root')
        const mockProjectDir = createMockDirectoryHandle('test-project')
        const binaryData = new ArrayBuffer(16)

        vi.mocked(filesystem.getOPFSRoot).mockResolvedValue(mockRoot)
        mockRoot.getDirectoryHandle = vi.fn().mockResolvedValue(mockProjectDir)

        vi.mocked(filesystem.directoryExists).mockResolvedValue(true)
        vi.mocked(filesystem.readFileFromDirectoryBinary).mockResolvedValue(binaryData)

        const result = await readAssetBinary('opfs', 'test-project', 'data.dat')

        expect(result.success).toBe(true)
        if (result.success) {
          expect(result.data).toBe(binaryData)
          expect(result.data).toBeInstanceOf(ArrayBuffer)
        }
      })
    })
  })

  // ============================================================================
  // Memory storage type — virtual in-memory filesystem
  // ============================================================================

  describe('memory storage type', () => {
    const PROJECT_ID = 'draft-test-memory'
    const STUB_PROJECT: NoodlesProjectJSON = {
      version: 14,
      nodes: [],
      edges: [],
      viewport: { x: 0, y: 0, zoom: 1 },
      timeline: {},
    }

    afterEach(() => {
      memoryProjectStore.deleteProject(PROJECT_ID)
    })

    describe('save + load round-trip', () => {
      it('saves project JSON to memory and loads it back', async () => {
        const saveResult = await save('memory', PROJECT_ID, STUB_PROJECT)
        expect(saveResult.success).toBe(true)

        const loadResult = await load('memory', PROJECT_ID)
        expect(loadResult.success).toBe(true)
        if (loadResult.success) {
          expect(loadResult.data.projectData.version).toBe(14)
          expect(loadResult.data.name).toBe(PROJECT_ID)
        }
      })

      it('load returns not-found for missing project', async () => {
        const result = await load('memory', 'nonexistent-draft')
        expect(result.success).toBe(false)
        if (!result.success) {
          expect(result.error.type).toBe('not-found')
        }
      })
    })

    describe('readAsset', () => {
      it('reads text asset from memory', async () => {
        memoryProjectStore.writeAsset(PROJECT_ID, 'cities.csv', 'name,pop\nNYC,8000000')

        const result = await readAsset('memory', PROJECT_ID, 'cities.csv')
        expect(result.success).toBe(true)
        if (result.success) {
          expect(result.data).toBe('name,pop\nNYC,8000000')
        }
      })

      it('returns not-found for missing asset', async () => {
        const result = await readAsset('memory', PROJECT_ID, 'missing.csv')
        expect(result.success).toBe(false)
        if (!result.success) {
          expect(result.error.type).toBe('not-found')
        }
      })

      it('does not touch filesystem APIs', async () => {
        memoryProjectStore.writeAsset(PROJECT_ID, 'test.csv', 'data')
        await readAsset('memory', PROJECT_ID, 'test.csv')

        expect(filesystem.selectDirectory).not.toHaveBeenCalled()
        expect(filesystem.readFileFromDirectory).not.toHaveBeenCalled()
        expect(filesystem.getOPFSRoot).not.toHaveBeenCalled()
      })
    })

    describe('readAssetBinary', () => {
      it('reads binary asset from memory', async () => {
        const bytes = new Uint8Array([10, 20, 30])
        memoryProjectStore.writeAsset(PROJECT_ID, 'img.png', new Blob([bytes]))

        const result = await readAssetBinary('memory', PROJECT_ID, 'img.png')
        expect(result.success).toBe(true)
        if (result.success) {
          expect(new Uint8Array(result.data)).toEqual(bytes)
        }
      })

      it('returns not-found for missing binary asset', async () => {
        const result = await readAssetBinary('memory', PROJECT_ID, 'missing.bin')
        expect(result.success).toBe(false)
        if (!result.success) {
          expect(result.error.type).toBe('not-found')
        }
      })
    })

    describe('writeAsset', () => {
      it('writes text asset to memory', async () => {
        const result = await writeAsset('memory', PROJECT_ID, 'new.csv', 'a,b\n1,2')
        expect(result.success).toBe(true)

        const readResult = await readAsset('memory', PROJECT_ID, 'new.csv')
        expect(readResult.success).toBe(true)
        if (readResult.success) {
          expect(readResult.data).toBe('a,b\n1,2')
        }
      })

      it('writes Blob asset to memory', async () => {
        const blob = new Blob(['blob data'])
        const result = await writeAsset('memory', PROJECT_ID, 'file.dat', blob)
        expect(result.success).toBe(true)

        const readResult = await readAsset('memory', PROJECT_ID, 'file.dat')
        expect(readResult.success).toBe(true)
        if (readResult.success) {
          expect(readResult.data).toBe('blob data')
        }
      })

      it('does not write to filesystem', async () => {
        await writeAsset('memory', PROJECT_ID, 'test.csv', 'x')

        expect(filesystem.writeFileToDirectory).not.toHaveBeenCalled()
        expect(filesystem.selectDirectory).not.toHaveBeenCalled()
      })
    })

    describe('checkAssetExists', () => {
      it('returns true for existing asset', async () => {
        memoryProjectStore.writeAsset(PROJECT_ID, 'data.csv', 'x')
        expect(await checkAssetExists('memory', PROJECT_ID, 'data.csv')).toBe(true)
      })

      it('returns false for missing asset', async () => {
        expect(await checkAssetExists('memory', PROJECT_ID, 'missing.csv')).toBe(false)
      })
    })

    describe('hasDataDirectory', () => {
      it('returns false when no assets', async () => {
        memoryProjectStore.setProjectJson(PROJECT_ID, STUB_PROJECT)
        expect(await hasDataDirectory('memory', PROJECT_ID)).toBe(false)
      })

      it('returns true when assets exist', async () => {
        memoryProjectStore.writeAsset(PROJECT_ID, 'file.csv', 'x')
        expect(await hasDataDirectory('memory', PROJECT_ID)).toBe(true)
      })
    })

    describe('listDataFiles', () => {
      it('lists all in-memory assets', async () => {
        memoryProjectStore.writeAsset(PROJECT_ID, 'a.csv', 'a')
        memoryProjectStore.writeAsset(PROJECT_ID, 'b.json', '{}')

        const result = await listDataFiles('memory', PROJECT_ID)
        expect(result.success).toBe(true)
        if (result.success) {
          expect(result.data).toContain('a.csv')
          expect(result.data).toContain('b.json')
          expect(result.data).toHaveLength(2)
        }
      })

      it('returns empty list for project with no assets', async () => {
        memoryProjectStore.setProjectJson(PROJECT_ID, STUB_PROJECT)
        const result = await listDataFiles('memory', PROJECT_ID)
        expect(result.success).toBe(true)
        if (result.success) {
          expect(result.data).toHaveLength(0)
        }
      })
    })

    describe('isolation from other storage types', () => {
      it('memory writes do not appear in fileSystemAccess reads', async () => {
        memoryProjectStore.writeAsset(PROJECT_ID, 'data.csv', 'in-memory')

        vi.mocked(directoryHandleCache.getCachedHandle).mockResolvedValue(null)
        vi.mocked(filesystem.selectDirectory).mockResolvedValue(null as unknown as FileSystemDirectoryHandle)

        const result = await readAsset('fileSystemAccess', PROJECT_ID, 'data.csv')
        expect(result.success).toBe(false)
      })

      it('memory operations never call filesystem APIs', async () => {
        memoryProjectStore.writeAsset(PROJECT_ID, 'test.csv', 'data')
        await readAsset('memory', PROJECT_ID, 'test.csv')
        await readAssetBinary('memory', PROJECT_ID, 'test.csv')
        await checkAssetExists('memory', PROJECT_ID, 'test.csv')
        await hasDataDirectory('memory', PROJECT_ID)
        await listDataFiles('memory', PROJECT_ID)

        expect(filesystem.selectDirectory).not.toHaveBeenCalled()
        expect(filesystem.readFileFromDirectory).not.toHaveBeenCalled()
        expect(filesystem.readFileFromDirectoryBinary).not.toHaveBeenCalled()
        expect(filesystem.writeFileToDirectory).not.toHaveBeenCalled()
        expect(filesystem.fileExists).not.toHaveBeenCalled()
        expect(filesystem.directoryExists).not.toHaveBeenCalled()
        expect(filesystem.getOPFSRoot).not.toHaveBeenCalled()
      })
    })
  })
})
