"$schema" = "https://conductor.build/schemas/settings.repo.schema.json"

[scripts]
setup = "(cd noodles-editor && npm install)"

[scripts.run.run]
available_in = "local"
command = "(cd noodles-editor && npm start)"
default = true
icon = "play"
