// Operator categories
export const categories = {
  code: ['Accessor', 'Code', 'DuckDb', 'JSON', 'Expression'],
  grouping: ['Container', 'ForLoop', 'ForLoopBegin', 'ForLoopEnd', 'GraphInput', 'GraphOutput'],
  color: ['CategoricalColorRamp', 'Color', 'ColorRamp', 'CombineRGBA', 'HSL', 'SplitRGBA'],
  data: [
    'Arc',
    'BoundingBox',
    'Bounds',
    'Chart',
    'Concat',
    'Cross',
    'DateTime',
    'DeckRenderer',
    'Directions',
    'File',
    'Filter',
    'Geocoder',
    'GeoParquet',
    'Merge',
    'Network',
    'Out',
    'RandomizeAttribute',
    'Scatter',
    'Select',
    'Shapefile',
    'Slice',
    'Sort',
    'Switch',
    'TableEditor',
    'TimeSeries',
    'Viewer',
    'ViewState',
  ],
  geojson: [
    'Clip',
    'Explode',
    'GeoEditor',
    'GeoJson',
    'GeoJsonTransform',
    'KmlToGeoJson',
    'LineToPolygon',
    'Point',
    'PolygonToLine',
    'Rectangle',
    'Reproject',
    'Smooth',
  ],
  geometry: [
    'Buffer',
    'Centroid',
    'ConvexHull',
    'Difference',
    'Dissolve',
    'HexGrid',
    'Intersect',
    'PointGrid',
    'Simplify',
    'SquareGrid',
    'TransformRotate',
    'TransformScale',
    'TransformTranslate',
    'Union',
    'Voronoi',
  ],
  analysis: [
    'Aggregate',
    'Along',
    'Area',
    'DBScanCluster',
    'Interpolate',
    'Isoline',
    'KMeansCluster',
    'Length',
    'LineSlice',
    'NearestPoint',
    'PointInPolygon',
    'SpatialJoin',
    'Tin',
  ],
  layer: [
    'A5Layer',
    'ArcLayer',
    'BitmapLayer',
    'ColumnLayer',
    'ContourLayer',
    'GeoJsonLayer',
    'GeohashLayer',
    'GreatCircleLayer',
    'GridCellLayer',
    'GridLayer',
    'H3ClusterLayer',
    'H3HexagonLayer',
    'HeatmapLayer',
    'HexagonLayer',
    'IconLayer',
    'LineLayer',
    'MVTLayer',
    'PathLayer',
    'PointCloudLayer',
    'PolygonLayer',
    'QuadkeyLayer',
    'RasterTileLayer',
    'S2Layer',
    'ScatterplotLayer',
    'ScenegraphLayer',
    'ScreenGridLayer',
    'SimpleMeshLayer',
    'SolidPolygonLayer',
    'TerrainLayer',
    'TextLayer',
    'Tile3DLayer',
    'TileLayer',
    'TripsLayer',
  ],
  extension: [
    'BrightnessContrastExtension',
    'BrushingExtension',
    'ClipExtension',
    'CollisionFilterExtension',
    'DataFilterExtension',
    'FillStyleExtension',
    'HueSaturationExtension',
    'Mask3DExtension',
    'MaskExtension',
    'PathStyleExtension',
    'TerrainExtension',
    'VibranceExtension',
  ],
  number: ['Number', 'MapRange', 'Extent', 'Math', 'BezierCurve', 'Ramp', 'Time'],
  string: ['String'],
  utility: [
    'Blending',
    'Boolean',
    'Console',
    'LayerProps',
    'MapStyleConfigurator',
    'Mouse',
    'Project',
    'Reroute',
    'Unproject',
  ],
  vector: ['CombineXY', 'CombineXYZ', 'SplitXY', 'SplitXYZ'],
  view: [
    'CustomMapLibreLayer',
    'FirstPersonView',
    'GlobeView',
    'MaplibreBasemap',
    'MapView',
    'MapViewState',
    'OrbitView',
    'OrthographicView',
    'PMTiles',
    'PointViewState',
    'SplitMapViewState',
    'XYZTile',
  ],
  widget: [
    'BitmapOverlayWidget',
    'CompassWidget',
    'FpsWidget',
    'FullscreenWidget',
    'LegendWidget',
    'ScaleWidget',
    'ScreenshotWidget',
    'ZoomWidget',
  ],
} as const

// TODO: Remove this function when we fully migrate to operator displayNames
export function nodeTypeToDisplayName(nodeType: string): string {
  return nodeType.replace(/Op$/, '')
}
