// Operator categories
export const categories = {
  code: ['Accessor', 'Code', 'DuckDb', 'JSON', 'Expression'],
  grouping: ['Container', 'ForLoop', 'ForLoopBegin', 'ForLoopEnd', 'GraphInput', 'GraphOutput'],
  color: ['CategoricalColorRamp', 'Color', 'ColorRamp', 'CombineRGBA', 'HSL', 'SplitRGBA'],
  data: [
    'Arc',
    'BoundingBox',
    'Bounds',
    'Chart',
    'Concat',
    'DateTime',
    'DeckRenderer',
    'Directions',
    'File',
    'Filter',
    'Geocoder',
    'Merge',
    'Network',
    'Out',
    'RandomizeAttribute',
    'Scatter',
    'Select',
    'Slice',
    'Sort',
    'Switch',
    'TableEditor',
    'TimeSeries',
    'Viewer',
    'ViewState',
  ],
  geojson: ['GeoJson', 'GeoJsonTransform', 'KmlToGeoJson', 'Point', 'Rectangle'],
  layer: [
    'A5Layer',
    'ArcLayer',
    'BitmapLayer',
    'ColumnLayer',
    'ContourLayer',
    'GeoJsonLayer',
    'GeohashLayer',
    'GreatCircleLayer',
    'GridCellLayer',
    'GridLayer',
    'H3ClusterLayer',
    'H3HexagonLayer',
    'HeatmapLayer',
    'HexagonLayer',
    'IconLayer',
    'LineLayer',
    'MVTLayer',
    'PathLayer',
    'PointCloudLayer',
    'PolygonLayer',
    'QuadkeyLayer',
    'RasterTileLayer',
    'S2Layer',
    'ScatterplotLayer',
    'ScenegraphLayer',
    'ScreenGridLayer',
    'SimpleMeshLayer',
    'SolidPolygonLayer',
    'TerrainLayer',
    'TextLayer',
    'Tile3DLayer',
    'TileLayer',
    'TripsLayer',
  ],
  extension: [
    'BrightnessContrastExtension',
    'BrushingExtension',
    'ClipExtension',
    'CollisionFilterExtension',
    'DataFilterExtension',
    'FillStyleExtension',
    'HueSaturationExtension',
    'Mask3DExtension',
    'MaskExtension',
    'PathStyleExtension',
    'TerrainExtension',
    'VibranceExtension',
  ],
  number: ['Number', 'MapRange', 'Extent', 'Math', 'BezierCurve', 'Time'],
  string: ['String'],
  utility: ['Boolean', 'Console', 'LayerProps', 'Mouse', 'Project', 'Unproject', 'MapStyle'],
  vector: ['CombineXY', 'CombineXYZ', 'SplitXY', 'SplitXYZ'],
  view: [
    'FirstPersonView',
    'GlobeView',
    'MaplibreBasemap',
    'MapView',
    'MapViewState',
    'OrbitView',
    'OrthographicView',
    'SplitMapViewState',
  ],
  widget: ['FpsWidget'],
} as const

// TODO: Remove this function when we fully migrate to operator displayNames
export function nodeTypeToDisplayName(nodeType: string): string {
  return nodeType.replace(/Op$/, '')
}
