blank_issues_enabled: false
contact_links:
  - name: I have a question / I need help
    url: https://github.com/joby-aviation/noodles.gl/discussions
    about: Ask generic questions or request help here
