// Uploads sourcemaps generated by the Vite build to Cloudflare R2, then rewrites
// the //# sourceMappingURL= comments in the built JS to point at the R2 URLs,
// and finally removes the .map files from dist/ so they don't end up in the
// GitHub Pages artifact.
//
// Required env vars:
//   GIT_SHA               – full git commit SHA (github.sha)
//   R2_ACCOUNT_ID         – Cloudflare account ID
//   R2_BUCKET_NAME        – R2 bucket name
//   SOURCEMAPS_PUBLIC_URL – public base URL, e.g. https://sourcemaps.noodles.gl
//   AWS_ACCESS_KEY_ID     – R2 API token key ID
//   AWS_SECRET_ACCESS_KEY – R2 API token secret
//   AWS_DEFAULT_REGION    – should be 'auto' for R2

import { execSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const distDir = path.resolve(__dirname, '../dist')

function requireEnv(name: string): string {
  const val = process.env[name]
  if (!val) throw new Error(`Missing required env var: ${name}`)
  return val
}

const sha = requireEnv('GIT_SHA')
const accountId = requireEnv('R2_ACCOUNT_ID')
const bucketName = requireEnv('R2_BUCKET_NAME')
const publicUrl = requireEnv('SOURCEMAPS_PUBLIC_URL').replace(/\/$/, '')

const r2Endpoint = `https://${accountId}.r2.cloudflarestorage.com`

// Walk a directory, yielding relative paths to files matching the predicate
function* walkFiles(dir: string, rel = ''): Generator<string> {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const relPath = rel ? `${rel}/${entry.name}` : entry.name
    if (entry.isDirectory()) {
      yield* walkFiles(path.join(dir, entry.name), relPath)
    } else {
      yield relPath
    }
  }
}

// Rewrite //# sourceMappingURL= comments in JS/MJS files to point at R2 URLs.
// Vite writes relative map filenames (e.g. index-abc.js.map), so we replace
// that with the absolute R2 URL including the SHA prefix.
function rewriteSourceMappingUrls() {
  for (const relPath of walkFiles(distDir)) {
    if (!relPath.endsWith('.js') && !relPath.endsWith('.mjs')) continue
    const absPath = path.join(distDir, relPath)
    const content = fs.readFileSync(absPath, 'utf8')
    // Only the very last line matters; avoid regex across the whole file
    const lastNewline = content.lastIndexOf('\n')
    const lastLine = content.slice(lastNewline + 1)
    if (!lastLine.startsWith('//# sourceMappingURL=')) continue

    const mapFilename = lastLine.slice('//# sourceMappingURL='.length).trim()
    // mapFilename is a bare filename like "index-abc.js.map" — build the full
    // R2 path by joining with the directory portion of the JS file's rel path
    const mapRelPath = path.join(path.dirname(relPath), mapFilename).replace(/\\/g, '/')
    const r2Url = `${publicUrl}/${sha}/${mapRelPath}`

    const rewritten = content.slice(0, lastNewline + 1) + `//# sourceMappingURL=${r2Url}\n`
    fs.writeFileSync(absPath, rewritten, 'utf8')
  }
}

// Sync all .map files from dist/ to R2 under the SHA prefix, then delete them locally.
function uploadAndRemoveMaps() {
  // Collect .map paths before we start deleting
  const mapFiles = [...walkFiles(distDir)].filter(p => p.endsWith('.map'))

  if (mapFiles.length === 0) {
    console.log('No .map files found in dist/ — skipping upload')
    return
  }

  console.log(`Uploading ${mapFiles.length} sourcemap(s) to R2 at ${sha}/...`)

  // aws s3 sync only the .map files by using --exclude '*' --include '*.map'
  execSync(
    `aws s3 sync "${distDir}/" "s3://${bucketName}/${sha}/"` +
      ` --endpoint-url "${r2Endpoint}"` +
      ` --exclude "*" --include "*.map"` +
      ` --no-progress`,
    { stdio: 'inherit', env: { ...process.env } },
  )

  // Write a ref marker so the cleanup job knows this SHA is the current production deploy
  const refContent = sha
  execSync(
    `echo -n "${refContent}" | aws s3 cp - "s3://${bucketName}/env-refs/production"` +
      ` --endpoint-url "${r2Endpoint}"` +
      ` --content-type "text/plain"`,
    { stdio: 'inherit', env: { ...process.env }, shell: true },
  )

  // Delete .map files from dist/ so they don't end up in the GitHub Pages artifact
  for (const relPath of mapFiles) {
    fs.unlinkSync(path.join(distDir, relPath))
  }
  console.log(`Removed ${mapFiles.length} .map file(s) from dist/`)
}

rewriteSourceMappingUrls()
uploadAndRemoveMaps()
