name: test

# Test on every pull request, and on push to main
on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: volta-cli/action@5c175f92dea6f48441c436471e6479dbc192e194 # v4.2.1
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: |
          cd noodles-editor
          yarn

      - name: Install playwright
        run: |
          cd noodles-editor
          npx playwright install chromium --with-deps

      - name: Check lint
        run: |
          cd noodles-editor
          # yarn lint

      - name: Run tests
        env:
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
          VITE_MAPTILER_API_KEY: ${{ secrets.VITE_MAPTILER_API_KEY }}
          VITE_MAPBOX_ACCESS_TOKEN: ${{ secrets.VITE_MAPBOX_ACCESS_TOKEN }}
          VITE_CESIUM_ACCESS_TOKEN: ${{ secrets.VITE_CESIUM_ACCESS_TOKEN }}
        run: |
          cd noodles-editor
          yarn test

  test-website:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: volta-cli/action@5c175f92dea6f48441c436471e6479dbc192e194 # v4.2.1
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: |
          cd website
          yarn

      - name: Build website
        run: |
          cd website
          yarn build
